# Generated by Django 4.1.1 on 2022-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_note_user_id_tag_user_id_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ex', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_in', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=150)),
                ('types', models.ManyToManyField(to='noteapp.incometype')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=150)),
                ('types', models.ManyToManyField(to='noteapp.expensestype')),
            ],
        ),
    ]
