# Generated by Django 4.1.1 on 2022-11-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_expensestype_incometype_income_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
